<#
.SYNOPSIS
    Generates deterministic synthetic seed data for the Bluegrass
    Glassworks demo database -> sql\seed_data.sql

.DESCRIPTION
    All data is fictional. A fixed random seed makes the output
    reproducible, so the committed seed_data.sql can always be
    regenerated. The schedule is anchored to -AnchorDate so the
    demo always has a live forward horizon.

.EXAMPLE
    .\Generate-SeedData.ps1 -AnchorDate 2026-08-06
#>
[CmdletBinding()]
param(
    [int]$Seed = 42,
    [string]$AnchorDate = (Get-Date -Format 'yyyy-MM-dd')
)

$rng    = [System.Random]::new($Seed)
$anchor = [datetime]::ParseExact($AnchorDate, 'yyyy-MM-dd', $null)
$root   = Split-Path $PSScriptRoot -Parent
$out    = Join-Path $root 'sql\seed_data.sql'

function Esc([string]$s) { $s -replace "'", "''" }

$sql = [System.Collections.Generic.List[string]]::new()
$sql.Add("-- Synthetic seed data generated by Generate-SeedData.ps1 (seed=$Seed, anchor=$AnchorDate)")
$sql.Add("-- ALL NAMES AND NUMBERS ARE FICTIONAL.")
$sql.Add("PRAGMA foreign_keys = ON;")

# ------------------------------------------------------------
# Customers
# ------------------------------------------------------------
$customers = @(
    @{ id=1; name='Old Kenton Distilling';  market='Spirits'  },
    @{ id=2; name='Limestone Spirits Co.';  market='Spirits'  },
    @{ id=3; name='River Bend Foods';       market='Food'     },
    @{ id=4; name='Meadowlark Preserves';   market='Food'     },
    @{ id=5; name='Cardinal Beverage Co.';  market='Beverage' },
    @{ id=6; name='Boone County Bottling';  market='Beverage' }
)
foreach ($c in $customers) {
    $sql.Add("INSERT INTO customers VALUES ($($c.id), '$(Esc $c.name)', '$($c.market)');")
}

# ------------------------------------------------------------
# Items — 16 bottle molds across the three markets
# ------------------------------------------------------------
$shapes = @{
    Spirits  = @('Spirits Round','Whiskey Flask','Decanter Square')
    Food     = @('Sauce Round','Mason Wide-Mouth','Condiment Hex')
    Beverage = @('Beverage Long-Neck','Juice Round','Soda Heritage')
}
$colors = @('Flint','Flint','Flint','Amber','Green')   # Flint-weighted
$mlOptions = @{
    Spirits  = @(375, 750, 750, 1000, 1750)
    Food     = @(240, 350, 473, 950)
    Beverage = @(355, 355, 473, 591)
}

$items = @()
for ($i = 0; $i -lt 16; $i++) {
    $cust  = $customers[$rng.Next($customers.Count)]
    $shape = $shapes[$cust.market][$rng.Next(3)]
    $ml    = $mlOptions[$cust.market][$rng.Next($mlOptions[$cust.market].Count)]
    $color = $colors[$rng.Next($colors.Count)]
    # glass weight scales roughly with capacity
    $wt    = [math]::Round(($ml * (0.018 + $rng.NextDouble() * 0.012)) + 4, 1)
    $no    = (41000 + $i * 137 + $rng.Next(40)).ToString()
    $items += @{ no=$no; desc="${ml}ml $shape - $color"; cust=$cust.id; ml=$ml; wt=$wt; color=$color }
}
foreach ($it in $items) {
    $sql.Add("INSERT INTO items VALUES ('$($it.no)', '$(Esc $it.desc)', $($it.cust), $($it.ml), $($it.wt), '$($it.color)');")
}

# ------------------------------------------------------------
# Load specs — every item gets a Bulk spec; ~half also Carton.
# glass_per_pallet derived from bottle size (bigger bottle =
# fewer per layer) x layer count.
# ------------------------------------------------------------
$bulkNo = 210100; $cartonNo = 160200
$loadSpecs = @()
foreach ($it in $items) {
    $perLayer = [math]::Max(40, [int](9000 / [math]::Sqrt($it.ml)) + $rng.Next(-15, 15))
    $layers   = 4 + $rng.Next(4)                     # 4-7
    $fp       = if ($rng.NextDouble() -lt 0.6) { '40x48' } else { '44x56' }
    $bulkNo++
    $loadSpecs += @{ no="$bulkNo"; item=$it.no; type='Bulk'; fp=$fp; layers=$layers
                     gpp=($perLayer * $layers); notes='Layer sheet on pallet and between each layer; wood top frame' }
    if ($rng.NextDouble() -lt 0.5) {
        $cLayers = $layers - 1
        $cartonNo++
        $loadSpecs += @{ no="$cartonNo"; item=$it.no; type='Carton'; fp=$fp; layers=$cLayers
                         gpp=[int]($perLayer * $cLayers * 0.82); notes='Cartons palletized; sheet between each layer' }
    }
}
foreach ($ls in $loadSpecs) {
    $sql.Add("INSERT INTO load_specs VALUES ('$($ls.no)', '$($ls.item)', '$($ls.type)', '$($ls.fp)', $($ls.layers), $($ls.gpp), '$(Esc $ls.notes)');")
}

# ------------------------------------------------------------
# Dunnage components
# ------------------------------------------------------------
$components = @(
    @{ id='PALLET_WOOD_40x48';   desc='Wood pallet 40x48';            cat='pallet';     itemno='103211' },
    @{ id='PALLET_WOOD_44x56';   desc='Wood pallet 44x56';            cat='pallet';     itemno='103478' },
    @{ id='TIERSHEET_40x48';     desc='Corrugated tier sheet 40x48';  cat='tier_sheet'; itemno='868355' },
    @{ id='TIERSHEET_44x56';     desc='Corrugated tier sheet 44x56';  cat='tier_sheet'; itemno='868412' },
    @{ id='TOPFRAME_WOOD_40x48'; desc='Wood top frame 40x48';         cat='top_frame';  itemno='106590' },
    @{ id='TOPFRAME_WOOD_44x56'; desc='Wood top frame 44x56';         cat='top_frame';  itemno='106613' },
    @{ id='HOOD_PLASTIC_40x48';  desc='Plastic hood 40x48';           cat='hood';       itemno='849102' },
    @{ id='HOOD_PLASTIC_44x56';  desc='Plastic hood 44x56';           cat='hood';       itemno='849117' }
)
foreach ($c in $components) {
    $sql.Add("INSERT INTO dunnage_components VALUES ('$($c.id)', '$(Esc $c.desc)', '$($c.cat)', '$($c.itemno)');")
}

# ------------------------------------------------------------
# Dunnage BOM (grain: load_spec x component)
#   Bulk:   pallet 1, tier sheets layers+1, top frame 1, hood ~40%
#   Carton: pallet 1, tier sheets layers-1
# ------------------------------------------------------------
foreach ($ls in $loadSpecs) {
    $fp = $ls.fp
    $sql.Add("INSERT INTO dunnage_bom VALUES ('$($ls.no)', 'PALLET_WOOD_$fp', 1);")
    if ($ls.type -eq 'Bulk') {
        $sql.Add("INSERT INTO dunnage_bom VALUES ('$($ls.no)', 'TIERSHEET_$fp', $($ls.layers + 1));")
        $sql.Add("INSERT INTO dunnage_bom VALUES ('$($ls.no)', 'TOPFRAME_WOOD_$fp', 1);")
        if ($rng.NextDouble() -lt 0.4) {
            $sql.Add("INSERT INTO dunnage_bom VALUES ('$($ls.no)', 'HOOD_PLASTIC_$fp', 1);")
        }
    } else {
        $sql.Add("INSERT INTO dunnage_bom VALUES ('$($ls.no)', 'TIERSHEET_$fp', $($ls.layers - 1));")
    }
}

# ------------------------------------------------------------
# Production lines + schedule.
# Each line is tiled with back-to-back campaign runs from
# anchor-14d to anchor+120d (mirrors a real machine Gantt).
# ------------------------------------------------------------
$lines = @(@{no=51; name='Line 51 - IS Machine A'}, @{no=52; name='Line 52 - IS Machine B'}, @{no=53; name='Line 53 - IS Machine C'})
foreach ($l in $lines) { $sql.Add("INSERT INTO production_lines VALUES ($($l.no), '$(Esc $l.name)');") }

$runId = 1
foreach ($l in $lines) {
    $cursor = $anchor.AddDays(-14)
    $horizon = $anchor.AddDays(120)
    while ($cursor -lt $horizon) {
        $ls    = $loadSpecs[$rng.Next($loadSpecs.Count)]
        $days  = 5 + $rng.Next(14)                     # 5-18 day campaigns
        $end   = $cursor.AddDays($days - 1)
        if ($end -gt $horizon) { $end = $horizon }
        $speed = [math]::Round(180 + $rng.NextDouble() * 240, 1)   # bottles/min
        $eff   = [math]::Round(0.80 + $rng.NextDouble() * 0.12, 2)
        $sql.Add("INSERT INTO production_schedule VALUES ($runId, $($l.no), '$($ls.item)', '$($ls.no)', '$($cursor.ToString('yyyy-MM-dd'))', '$($end.ToString('yyyy-MM-dd'))', $speed, $eff);")
        $runId++
        $cursor = $end.AddDays(1)
    }
}

# ------------------------------------------------------------
# On-hand inventory — partial coverage so the net MRP shows
# both covered days and real shortfalls.
# ------------------------------------------------------------
$onHand = @{
    'PALLET_WOOD_40x48'   = 2600
    'PALLET_WOOD_44x56'   = 1450
    'TIERSHEET_40x48'     = 21000
    'TIERSHEET_44x56'     = 9800
    'TOPFRAME_WOOD_40x48' = 900
    'TOPFRAME_WOOD_44x56' = 620
    'HOOD_PLASTIC_40x48'  = 400
    'HOOD_PLASTIC_44x56'  = 150
}
foreach ($k in $onHand.Keys | Sort-Object) {
    $sql.Add("INSERT INTO dunnage_on_hand VALUES ('$k', $($onHand[$k]));")
}

Set-Content -Path $out -Value ($sql -join "`r`n") -Encoding utf8
Write-Host "Wrote $($sql.Count) SQL lines -> $out"
Write-Host "Items: $($items.Count) | Load specs: $($loadSpecs.Count) | Runs: $($runId - 1)"
